version: "3.7"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 18080:8080
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=kitchen
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db-data:/var/lib/mysql